# Generated by Django 4.2.11 on 2024-05-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('phoneno', models.CharField(default='', max_length=10)),
                ('address_line1', models.TextField(default='')),
                ('address_line2', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=50)),
                ('pincode', models.IntegerField(default=0)),
            ],
        ),
    ]
